{% set version = "3.0.3" %}
{% set sha256 = "f9b9956fe29fcc259e26800538f3b10c28aa4d7dfbef7093095ca151545dbe3d" %}

package:
  name: motus
  version: '{{ version }}'

source:
  url: https://github.com/motu-tool/mOTUs/archive/{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 0
  # motus requires python3
  #skip: True # [not py3k]
  noarch: python

requirements:
  build:
     - python >=3.8
  host:
    - python >=3.8
  run:
    - metasnv =1.0.3
    - samtools >=1.9
    - bwa >=0.7.17
    - python >=3.8

test:
  commands:
    - motus --version

about:
  home: http://motu-tool.org/
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Marker gene-based OTU (mOTU) profiling
  dev_url: https://github.com/motu-tool/mOTUs

extra:
  notes: A tiny wrapper to the command motus was added. See build.sh for additional notes
  identifiers:
    - biotools:motus
  recipe-maintainers:
    - AlessioMilanese
