{% set name = "perl-compress-raw-zlib" %}
{% set version = "2.202" %}
{% set sha256 = "96e20946eb457a32d2d7a0050b922e37b5ada41246bcdc824196d3f7c4da91b7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Zlib-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Compress::Raw::Zlib

about:
  home: http://metacpan.org/pod/Compress::Raw::Zlib
  license: perl_5
  summary: 'Basic utilities for writing tests.'
